# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app_ticket:
            types:
                ticket:
                    properties:
                        subject: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Ticket
                        provider: ~
                        finder: ~
