knp_paginator:
    page_range: 10 # liczba linków w numeracji stron
    default_options:
        page_name: page # nazwa zmiennej w adresie Url, np: ?page=1              
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'